/**
 * Skill audit catalog — expected trigger / behaviour for regression review.
 * status: ok | partial | missing
 */
export type SkillStatus = 'ok' | 'partial' | 'missing'

export interface SkillSpec {
  id: string
  name: string
  owners: string[]
  trigger: string
  behaviour: string
  status: SkillStatus
  /** Substring(s) expected in game log when skill fires */
  logHints: string[]
}

export const SKILL_CATALOG: SkillSpec[] = [
  {
    id: 'jianxiong',
    name: '奸雄',
    owners: ['caocao'],
    trigger: '受到傷害後（存活）',
    behaviour: '可選擇獲得造成傷害的牌（可拒絕）',
    status: 'ok',
    logHints: ['奸雄'],
  },
  {
    id: 'yaowu',
    name: '耀武',
    owners: ['huaxiong'],
    trigger: '受到紅色【殺】傷害時',
    behaviour: '傷害來源選擇：回覆1體力或摸一張牌',
    status: 'ok',
    logHints: ['耀武'],
  },
  {
    id: 'fankui',
    name: '反饋',
    owners: ['simayi'],
    trigger: '受到傷害後（存活）且來源有牌',
    behaviour: '選擇獲得傷害來源一張牌',
    status: 'ok',
    logHints: ['反饋'],
  },
  {
    id: 'guicai',
    name: '鬼才',
    owners: ['simayi'],
    trigger: '判定牌生效前',
    behaviour: '有對應花色時自動替換判定牌',
    status: 'ok',
    logHints: ['鬼才'],
  },
  {
    id: 'ganglie',
    name: '剛烈',
    owners: ['xiahoudun'],
    trigger: '受到傷害後（存活）',
    behaviour: '判定非紅桃：來源棄兩張或受1傷',
    status: 'ok',
    logHints: ['剛烈'],
  },
  {
    id: 'tuxi',
    name: '突襲',
    owners: ['zhangliao'],
    trigger: '摸牌階段',
    behaviour: '少摸一張並獲得一名其他角色一張手牌',
    status: 'ok',
    logHints: ['突襲'],
  },
  {
    id: 'luoyi',
    name: '裸衣',
    owners: ['xuchu'],
    trigger: '出牌階段主動',
    behaviour: '棄兩張：本回合殺+1傷害且不能用錦囊',
    status: 'ok',
    logHints: ['裸衣'],
  },
  {
    id: 'tiandu',
    name: '天妒',
    owners: ['guojia'],
    trigger: '判定牌生效後',
    behaviour: '可獲得判定牌',
    status: 'ok',
    logHints: ['天妒'],
  },
  {
    id: 'yiji',
    name: '遺計',
    owners: ['guojia'],
    trigger: '每受到1點傷害後（瀕死前）',
    behaviour: '摸兩張牌（每點傷害）',
    status: 'ok',
    logHints: ['遺計'],
  },
  {
    id: 'luoshen',
    name: '洛神',
    owners: ['zhenji'],
    trigger: '準備階段',
    behaviour: '判定黑色則獲得，可重複至紅色',
    status: 'ok',
    logHints: ['洛神'],
  },
  {
    id: 'qingguo',
    name: '傾國',
    owners: ['zhenji'],
    trigger: '需要閃／當閃使用時',
    behaviour: '黑色牌可當閃',
    status: 'ok',
    logHints: [],
  },
  {
    id: 'rende',
    name: '仁德',
    owners: ['liubei'],
    trigger: '出牌階段主動',
    behaviour: '交手牌；本回合交≥2張回1體力',
    status: 'ok',
    logHints: ['仁德'],
  },
  {
    id: 'wusheng',
    name: '武聖',
    owners: ['guanyu'],
    trigger: '使用牌時',
    behaviour: '紅色牌可當殺',
    status: 'ok',
    logHints: [],
  },
  {
    id: 'paoxiao',
    name: '咆哮',
    owners: ['zhangfei'],
    trigger: '出牌階段',
    behaviour: '可使用任意張殺',
    status: 'ok',
    logHints: [],
  },
  {
    id: 'guanxing',
    name: '觀星',
    owners: ['zhugeliang'],
    trigger: '準備階段',
    behaviour: '觀看牌堆頂：保留／反轉／置底',
    status: 'ok',
    logHints: ['觀星'],
  },
  {
    id: 'kongcheng',
    name: '空城',
    owners: ['zhugeliang'],
    trigger: '成為殺的目標時',
    behaviour: '手牌為0時不能成為殺的目標',
    status: 'ok',
    logHints: [],
  },
  {
    id: 'longdan',
    name: '龍膽',
    owners: ['zhaoyun'],
    trigger: '使用／打出殺或閃時',
    behaviour: '殺可當閃，閃可當殺',
    status: 'ok',
    logHints: [],
  },
  {
    id: 'mashu',
    name: '馬術',
    owners: ['machao'],
    trigger: '計算距離時',
    behaviour: '距離-1',
    status: 'ok',
    logHints: [],
  },
  {
    id: 'tieqi',
    name: '鐵騎',
    owners: ['machao'],
    trigger: '使用殺指定目標後',
    behaviour: '判定紅色則目標不能出閃',
    status: 'ok',
    logHints: ['鐵騎'],
  },
  {
    id: 'jizhi',
    name: '集智',
    owners: ['huangyueying'],
    trigger: '使用錦囊後',
    behaviour: '摸一張牌',
    status: 'ok',
    logHints: ['集智'],
  },
  {
    id: 'qicai',
    name: '奇才',
    owners: ['huangyueying'],
    trigger: '使用錦囊選目標時',
    behaviour: '錦囊無距離限制',
    status: 'ok',
    logHints: [],
  },
  {
    id: 'zhiheng',
    name: '制衡',
    owners: ['sunquan'],
    trigger: '出牌階段限一次',
    behaviour: '棄任意張摸等量',
    status: 'ok',
    logHints: ['制衡'],
  },
  {
    id: 'qixi',
    name: '奇襲',
    owners: ['ganning'],
    trigger: '使用牌時',
    behaviour: '黑色牌可當過河拆橋',
    status: 'ok',
    logHints: [],
  },
  {
    id: 'keji',
    name: '克己',
    owners: ['lvmeng'],
    trigger: '棄牌階段前',
    behaviour: '若本回合未出殺則跳過棄牌',
    status: 'ok',
    logHints: ['克己'],
  },
  {
    id: 'kurou',
    name: '苦肉',
    owners: ['huanggai'],
    trigger: '出牌階段主動',
    behaviour: '失去1體力，摸兩張',
    status: 'ok',
    logHints: ['苦肉'],
  },
  {
    id: 'yingzi',
    name: '英姿',
    owners: ['zhouyu'],
    trigger: '摸牌階段',
    behaviour: '多摸一張',
    status: 'ok',
    logHints: [],
  },
  {
    id: 'fanjian',
    name: '反間',
    owners: ['zhouyu'],
    trigger: '出牌階段主動',
    behaviour: '交給對方一張牌並令其猜花色',
    status: 'ok',
    logHints: ['反間'],
  },
  {
    id: 'guose',
    name: '國色',
    owners: ['daqiao'],
    trigger: '使用牌時',
    behaviour: '方塊可當樂不思蜀',
    status: 'ok',
    logHints: ['國色'],
  },
  {
    id: 'liuli',
    name: '流離',
    owners: ['daqiao'],
    trigger: '成為殺的目標時',
    behaviour: '棄一張牌將殺轉移',
    status: 'ok',
    logHints: ['流離'],
  },
  {
    id: 'qianxun',
    name: '謙遜',
    owners: ['luxun'],
    trigger: '成為順手牽羊目標時',
    behaviour: '不能成為順手牽羊的目標',
    status: 'ok',
    logHints: [],
  },
  {
    id: 'lianying',
    name: '連營',
    owners: ['luxun'],
    trigger: '失去最後一張手牌時',
    behaviour: '摸一張牌',
    status: 'ok',
    logHints: ['連營'],
  },
  {
    id: 'jieyin',
    name: '結姻',
    owners: ['sunshangxiang'],
    trigger: '出牌階段限一次',
    behaviour: '棄兩張牌令自己與一名男性各回1',
    status: 'ok',
    logHints: ['結姻'],
  },
  {
    id: 'xiaoji',
    name: '梟姬',
    owners: ['sunshangxiang'],
    trigger: '失去裝備時',
    behaviour: '摸兩張牌',
    status: 'ok',
    logHints: ['梟姬'],
  },
  {
    id: 'jijiu',
    name: '急救',
    owners: ['huatuo'],
    trigger: '需要桃時',
    behaviour: '紅牌可當桃',
    status: 'ok',
    logHints: [],
  },
  {
    id: 'qingnang',
    name: '青囊',
    owners: ['huatuo'],
    trigger: '出牌階段限一次',
    behaviour: '棄一張牌令一名角色回1體力',
    status: 'ok',
    logHints: ['青囊'],
  },
  {
    id: 'wushuang',
    name: '無雙',
    owners: ['lvbu'],
    trigger: '使用殺時',
    behaviour: '需兩張閃抵消',
    status: 'ok',
    logHints: ['無雙'],
  },
  {
    id: 'lijian',
    name: '離間',
    owners: ['diaochan'],
    trigger: '出牌階段限一次',
    behaviour: '棄一張牌令兩名男性決鬥',
    status: 'ok',
    logHints: ['離間'],
  },
  {
    id: 'biyue',
    name: '閉月',
    owners: ['diaochan'],
    trigger: '結束出牌／結束階段',
    behaviour: '摸一張牌',
    status: 'ok',
    logHints: ['閉月'],
  },
  {
    id: 'leiji',
    name: '雷擊',
    owners: ['zhangjiao'],
    trigger: '使用／打出閃後',
    behaviour: '令一名角色判定，黑色則雷電傷害',
    status: 'ok',
    logHints: ['雷擊'],
  },
  {
    id: 'guidao',
    name: '鬼道',
    owners: ['zhangjiao'],
    trigger: '判定牌生效前',
    behaviour: '有對應黑色牌時自動替換判定牌',
    status: 'ok',
    logHints: ['鬼道'],
  },
  {
    id: 'liegong',
    name: '烈弓',
    owners: ['huangzhong'],
    trigger: '使用殺指定目標時',
    behaviour: '目標手牌數≥己則不能出閃',
    status: 'ok',
    logHints: ['烈弓'],
  },
  {
    id: 'kuanggu',
    name: '狂骨',
    owners: ['weiyan'],
    trigger: '對距離1角色造成傷害後',
    behaviour: '回復1體力',
    status: 'ok',
    logHints: ['狂骨'],
  },
  {
    id: 'buqu',
    name: '不屈',
    owners: ['zhoutai'],
    trigger: '瀕死',
    behaviour: '摸一張後若有手牌則回至1體力',
    status: 'ok',
    logHints: ['不屈'],
  },
  {
    id: 'jieming',
    name: '節命',
    owners: ['xunyu'],
    trigger: '受到傷害後',
    behaviour: '令一名角色摸其已損失體力數（至少1）',
    status: 'ok',
    logHints: ['節命'],
  },
  {
    id: 'xingshang',
    name: '行殤',
    owners: ['caopi'],
    trigger: '其他角色死亡時',
    behaviour: '摸兩張牌',
    status: 'ok',
    logHints: ['行殤'],
  },
  {
    id: 'jiang',
    name: '激昂',
    owners: ['sunce'],
    trigger: '使用或成為殺／決鬥目標時',
    behaviour: '摸一張牌',
    status: 'ok',
    logHints: ['激昂'],
  },
  {
    id: 'qiangxi',
    name: '強襲',
    owners: ['dianwei'],
    trigger: '出牌階段限一次',
    behaviour: '失去1體力或棄武器，對攻擊範圍內造成1傷害',
    status: 'ok',
    logHints: ['強襲'],
  },
]
