/**
 * Skill audit catalog — expected trigger / behaviour for regression review.
 * status: ok | partial | missing
 */
export type SkillStatus = 'ok' | 'partial' | 'missing'

export interface SkillSpec {
  id: string
  name: string
  owners: string[]
  trigger: string
  behaviour: string
  status: SkillStatus
  /** Substring(s) expected in game log when skill fires */
  logHints: string[]
}

export const SKILL_CATALOG: SkillSpec[] = [
  {
    id: 'jianxiong',
    name: '奸雄',
    owners: ['caocao'],
    trigger: '受到傷害後（存活）',
    behaviour: '可選擇獲得造成傷害的牌（可拒絕）',
    status: 'ok',
    logHints: ['奸雄'],
  },
  {
    id: 'yaowu',
    name: '耀武',
    owners: ['huaxiong'],
    trigger: '受到紅色【殺】傷害時',
    behaviour: '傷害來源選擇：回覆1體力或摸一張牌',
    status: 'ok',
    logHints: ['耀武'],
  },
  {
    id: 'fankui',
    name: '反饋',
    owners: ['simayi'],
    trigger: '受到傷害後（存活）且來源有牌',
    behaviour: '選擇獲得傷害來源一張牌',
    status: 'ok',
    logHints: ['反饋'],
  },
  {
    id: 'guicai',
    name: '鬼才',
    owners: ['simayi'],
    trigger: '判定牌生效前',
    behaviour: '有對應花色時自動替換判定牌',
    status: 'ok',
    logHints: ['鬼才'],
  },
  {
    id: 'ganglie',
    name: '剛烈',
    owners: ['xiahoudun'],
    trigger: '受到傷害後（存活）',
    behaviour: '判定非紅桃：來源棄兩張或受1傷',
    status: 'ok',
    logHints: ['剛烈'],
  },
  {
    id: 'tuxi',
    name: '突襲',
    owners: ['zhangliao'],
    trigger: '摸牌階段',
    behaviour: '少摸一張並獲得一名其他角色一張手牌',
    status: 'ok',
    logHints: ['突襲'],
  },
  {
    id: 'luoyi',
    name: '裸衣',
    owners: ['xuchu'],
    trigger: '出牌階段主動',
    behaviour: '棄兩張：本回合殺+1傷害且不能用錦囊',
    status: 'ok',
    logHints: ['裸衣'],
  },
  {
    id: 'tiandu',
    name: '天妒',
    owners: ['guojia'],
    trigger: '判定牌生效後',
    behaviour: '可獲得判定牌',
    status: 'ok',
    logHints: ['天妒'],
  },
  {
    id: 'yiji',
    name: '遺計',
    owners: ['guojia'],
    trigger: '每受到1點傷害後（瀕死前）',
    behaviour: '摸兩張牌（每點傷害）',
    status: 'ok',
    logHints: ['遺計'],
  },
  {
    id: 'luoshen',
    name: '洛神',
    owners: ['zhenji'],
    trigger: '準備階段',
    behaviour: '判定黑色則獲得，可重複至紅色',
    status: 'ok',
    logHints: ['洛神'],
  },
  {
    id: 'qingguo',
    name: '傾國',
    owners: ['zhenji'],
    trigger: '需要閃／當閃使用時',
    behaviour: '黑色牌可當閃',
    status: 'ok',
    logHints: [],
  },
  {
    id: 'rende',
    name: '仁德',
    owners: ['liubei'],
    trigger: '出牌階段主動',
    behaviour: '交手牌；本回合交≥2張回1體力',
    status: 'ok',
    logHints: ['仁德'],
  },
  {
    id: 'wusheng',
    name: '武聖',
    owners: ['guanyu'],
    trigger: '使用牌時',
    behaviour: '紅色牌可當殺',
    status: 'ok',
    logHints: [],
  },
  {
    id: 'paoxiao',
    name: '咆哮',
    owners: ['zhangfei'],
    trigger: '出牌階段',
    behaviour: '可使用任意張殺',
    status: 'ok',
    logHints: [],
  },
  {
    id: 'guanxing',
    name: '觀星',
    owners: ['zhugeliang'],
    trigger: '準備階段',
    behaviour: '觀看牌堆頂：保留／反轉／置底',
    status: 'ok',
    logHints: ['觀星'],
  },
  {
    id: 'kongcheng',
    name: '空城',
    owners: ['zhugeliang'],
    trigger: '成為殺的目標時',
    behaviour: '手牌為0時不能成為殺的目標',
    status: 'ok',
    logHints: [],
  },
  {
    id: 'longdan',
    name: '龍膽',
    owners: ['zhaoyun'],
    trigger: '使用／打出殺或閃時',
    behaviour: '殺可當閃，閃可當殺',
    status: 'ok',
    logHints: [],
  },
  {
    id: 'mashu',
    name: '馬術',
    owners: ['machao'],
    trigger: '計算距離時',
    behaviour: '距離-1',
    status: 'ok',
    logHints: [],
  },
  {
    id: 'tieqi',
    name: '鐵騎',
    owners: ['machao'],
    trigger: '使用殺指定目標後',
    behaviour: '判定紅色則目標不能出閃',
    status: 'ok',
    logHints: ['鐵騎'],
  },
  {
    id: 'jizhi',
    name: '集智',
    owners: ['huangyueying'],
    trigger: '使用錦囊後',
    behaviour: '摸一張牌',
    status: 'ok',
    logHints: ['集智'],
  },
  {
    id: 'qicai',
    name: '奇才',
    owners: ['huangyueying'],
    trigger: '使用錦囊選目標時',
    behaviour: '錦囊無距離限制',
    status: 'ok',
    logHints: [],
  },
  {
    id: 'zhiheng',
    name: '制衡',
    owners: ['sunquan'],
    trigger: '出牌階段限一次',
    behaviour: '棄任意張摸等量',
    status: 'ok',
    logHints: ['制衡'],
  },
  {
    id: 'qixi',
    name: '奇襲',
    owners: ['ganning'],
    trigger: '使用牌時',
    behaviour: '黑色牌可當過河拆橋',
    status: 'ok',
    logHints: [],
  },
  {
    id: 'keji',
    name: '克己',
    owners: ['lvmeng'],
    trigger: '棄牌階段前',
    behaviour: '若本回合未出殺則跳過棄牌',
    status: 'ok',
    logHints: ['克己'],
  },
  {
    id: 'kurou',
    name: '苦肉',
    owners: ['huanggai'],
    trigger: '出牌階段主動',
    behaviour: '失去1體力，摸兩張',
    status: 'ok',
    logHints: ['苦肉'],
  },
  {
    id: 'yingzi',
    name: '英姿',
    owners: ['zhouyu'],
    trigger: '摸牌階段',
    behaviour: '多摸一張',
    status: 'ok',
    logHints: [],
  },
  {
    id: 'fanjian',
    name: '反間',
    owners: ['zhouyu'],
    trigger: '出牌階段主動',
    behaviour: '交給對方一張牌並令其猜花色',
    status: 'ok',
    logHints: ['反間'],
  },
  {
    id: 'guose',
    name: '國色',
    owners: ['daqiao'],
    trigger: '使用牌時',
    behaviour: '方塊可當樂不思蜀',
    status: 'ok',
    logHints: ['國色'],
  },
  {
    id: 'liuli',
    name: '流離',
    owners: ['daqiao'],
    trigger: '成為殺的目標時',
    behaviour: '棄一張牌將殺轉移',
    status: 'ok',
    logHints: ['流離'],
  },
  {
    id: 'qianxun',
    name: '謙遜',
    owners: ['luxun'],
    trigger: '成為順手牽羊目標時',
    behaviour: '不能成為順手牽羊的目標',
    status: 'ok',
    logHints: [],
  },
  {
    id: 'lianying',
    name: '連營',
    owners: ['luxun'],
    trigger: '失去最後一張手牌時',
    behaviour: '摸一張牌',
    status: 'ok',
    logHints: ['連營'],
  },
  {
    id: 'jieyin',
    name: '結姻',
    owners: ['sunshangxiang'],
    trigger: '出牌階段限一次',
    behaviour: '棄兩張牌令自己與一名男性各回1',
    status: 'ok',
    logHints: ['結姻'],
  },
  {
    id: 'xiaoji',
    name: '梟姬',
    owners: ['sunshangxiang'],
    trigger: '失去裝備時',
    behaviour: '摸兩張牌',
    status: 'ok',
    logHints: ['梟姬'],
  },
  {
    id: 'jijiu',
    name: '急救',
    owners: ['huatuo'],
    trigger: '需要桃時',
    behaviour: '紅牌可當桃',
    status: 'ok',
    logHints: [],
  },
  {
    id: 'qingnang',
    name: '青囊',
    owners: ['huatuo'],
    trigger: '出牌階段限一次',
    behaviour: '棄一張牌令一名角色回1體力',
    status: 'ok',
    logHints: ['青囊'],
  },
  {
    id: 'wushuang',
    name: '無雙',
    owners: ['lvbu'],
    trigger: '使用殺時',
    behaviour: '需兩張閃抵消',
    status: 'ok',
    logHints: ['無雙'],
  },
  {
    id: 'lijian',
    name: '離間',
    owners: ['diaochan'],
    trigger: '出牌階段限一次',
    behaviour: '棄一張牌令兩名男性決鬥',
    status: 'ok',
    logHints: ['離間'],
  },
  {
    id: 'biyue',
    name: '閉月',
    owners: ['diaochan'],
    trigger: '結束出牌／結束階段',
    behaviour: '摸一張牌',
    status: 'ok',
    logHints: ['閉月'],
  },
  {
    id: 'leiji',
    name: '雷擊',
    owners: ['zhangjiao'],
    trigger: '使用／打出閃後',
    behaviour: '令一名角色判定，黑色則雷電傷害',
    status: 'ok',
    logHints: ['雷擊'],
  },
  {
    id: 'guidao',
    name: '鬼道',
    owners: ['zhangjiao'],
    trigger: '判定牌生效前',
    behaviour: '有對應黑色牌時自動替換判定牌',
    status: 'ok',
    logHints: ['鬼道'],
  },
  {
    id: 'liegong',
    name: '烈弓',
    owners: ['huangzhong'],
    trigger: '使用殺指定目標時',
    behaviour: '目標手牌數≥己則不能出閃',
    status: 'ok',
    logHints: ['烈弓'],
  },
  {
    id: 'kuanggu',
    name: '狂骨',
    owners: ['weiyan'],
    trigger: '對距離1角色造成傷害後',
    behaviour: '回復1體力',
    status: 'ok',
    logHints: ['狂骨'],
  },
  {
    id: 'buqu',
    name: '不屈',
    owners: ['zhoutai'],
    trigger: '瀕死',
    behaviour: '摸一張後若有手牌則回至1體力',
    status: 'ok',
    logHints: ['不屈'],
  },
  {
    id: 'jieming',
    name: '節命',
    owners: ['xunyu'],
    trigger: '受到傷害後',
    behaviour: '令一名角色摸其已損失體力數（至少1）',
    status: 'ok',
    logHints: ['節命'],
  },
  {
    id: 'xingshang',
    name: '行殤',
    owners: ['caopi'],
    trigger: '其他角色死亡時',
    behaviour: '摸兩張牌',
    status: 'ok',
    logHints: ['行殤'],
  },
  {
    id: 'jiang',
    name: '激昂',
    owners: ['sunce'],
    trigger: '使用或成為殺／決鬥目標時',
    behaviour: '摸一張牌',
    status: 'ok',
    logHints: ['激昂'],
  },
  {
    id: 'qiangxi',
    name: '強襲',
    owners: ['dianwei'],
    trigger: '出牌階段限一次',
    behaviour: '失去1體力或棄武器，對攻擊範圍內造成1傷害',
    status: 'ok',
    logHints: ['強襲'],
  },
  ...([
    ['shensu', '神速', ['xiahouyuan'], '摸牌階段前', '跳過摸牌，本回合殺無距離限制'],
    ['jushou', '據守', ['caoren'], '出牌階段結束', '摸四張並跳過下回合出牌'],
    ['tianxiang', '天香', ['xiaoqiao'], '受到傷害前', '棄紅桃手牌轉移傷害'],
    ['hongyan', '紅顏', ['xiaoqiao'], '花色計算', '黑桃視為紅桃'],
    ['guhuo', '蠱惑', ['yuji'], '出牌階段限一次', '手牌可轉換為四種牌'],
    ['quhu', '驅虎', ['xunyu'], '出牌階段限一次', '與高體力角色拼點並造成傷害'],
    ['lianhuan', '連環', ['pangtong'], '使用牌時', '梅花牌可當鐵索連環'],
    ['niepan', '涅槃', ['pangtong'], '瀕死', '限定一次重置牌區並回復摸牌'],
    ['bazhen', '八陣', ['wolong'], '需要閃時', '無防具時視為八卦陣'],
    ['huoji', '火計', ['wolong'], '使用牌時', '紅牌可當火攻'],
    ['kanpo', '看破', ['wolong'], '無懈詢問', '黑牌可當無懈可擊'],
    ['tianyi', '天義', ['taishici'], '出牌階段限一次', '拼點決定本回合殺強化或禁用'],
    ['mengjin', '猛進', ['pangde'], '殺被閃避後', '棄置目標一張牌'],
    ['shuangxiong', '雙雄', ['yanliangwenchou'], '摸牌階段前', '判定並將異色牌當決鬥'],
    ['duanliang', '斷糧', ['xuhuang'], '使用牌時', '黑色基本或裝備牌當兵糧'],
    ['fangzhu', '放逐', ['caopi'], '受到傷害後', '令他人摸牌並跳過下回合出牌'],
    ['huoshou', '禍首', ['menghuo'], '南蠻入侵', '免疫並接管傷害來源'],
    ['zaiqi', '再起', ['menghuo'], '摸牌階段', '展示牌並以紅桃回復'],
    ['juxiang', '巨象', ['zhurong'], '南蠻入侵', '免疫並在結算後摸牌'],
    ['lieren', '烈刃', ['zhurong'], '殺造成傷害後', '拼點勝利獲得目標手牌'],
    ['yinghun', '英魂', ['sunjian'], '準備階段', '令他人摸牌並棄牌'],
    ['haoshi', '好施', ['lusu'], '摸牌階段', '多摸兩張並分出半數手牌'],
    ['dimeng', '締盟', ['lusu'], '出牌階段限一次', '棄差額並交換兩人手牌'],
    ['weimu', '帷幕', ['jiaxu'], '成為錦囊目標', '免疫黑色指定目標錦囊'],
    ['wansha', '完殺', ['jiaxu'], '瀕死救援', '回合內僅自己可以使用桃'],
    ['luanwu', '亂武', ['jiaxu'], '出牌階段限定一次', '其他角色依次失去體力'],
    ['qiaobian', '巧變', ['zhanghe'], '出牌階段限一次', '棄牌並摸牌'],
    ['tuntian', '屯田', ['dengai'], '回合外失去手牌', '累積田並縮短距離'],
    ['zaoxian', '鑿險', ['dengai'], '準備階段', '三田覺醒並獲得急襲'],
    ['jixi', '急襲', ['dengai'], '出牌階段', '消耗田使用順手牽羊'],
    ['tiaoxin', '挑釁', ['jiangwei'], '出牌階段限一次', '令目標出殺或棄牌'],
    ['zhiji', '志繼', ['jiangwei'], '準備階段', '空手覺醒並獲得觀星'],
    ['xiangle', '享樂', ['liushan'], '成為殺目標', '來源須額外棄基本牌'],
    ['fangquan', '放權', ['liushan'], '出牌階段', '結束出牌並令他人摸牌'],
    ['hunzi', '魂姿', ['sunce'], '準備階段', '低體力覺醒獲得英姿英魂'],
    ['zhiba', '制霸', ['sunce'], '出牌階段', '與每名角色各拼點一次'],
    ['zhijian', '直諫', ['zhangzhaozhanghong'], '出牌階段', '為他人裝備並摸牌'],
    ['guzheng', '固政', ['zhangzhaozhanghong'], '他人棄牌結束', '摸一張牌'],
    ['huashen', '化身', ['zuoci'], '首次準備階段', '隨機獲得已實作技能'],
    ['xinsheng', '新生', ['zuoci'], '受到傷害後', '重新隨機化身技能'],
    ['beige', '悲歌', ['caiwenji'], '殺造成傷害後', '棄牌判定並按花色處理'],
    ['duanchang', '斷腸', ['caiwenji'], '死亡時', '令殺手失去全部武將技能'],
    ['enyuan', '恩怨', ['fazheng'], '受到傷害後', '傷害來源交一張手牌或失去1點體力'],
    ['xuanhuo', '眩惑', ['fazheng'], '準備階段', '跳過摸牌令他人摸二，再獲得其至多兩張牌'],
    ['pojun', '破軍', ['xusheng'], '殺造成傷害後', '目標摸當前體力值張牌並跳過下個出牌階段'],
    ['ganlu', '甘露', ['wuguotai'], '出牌階段限一次', '交換兩名角色的裝備區'],
    ['buyi', '補益', ['wuguotai'], '角色瀕死時', '展示非基本手牌並棄置，使其回復1點體力'],
    ['xiansi', '陷嗣', ['liufeng'], '準備階段／成為殺目標／出牌階段', '累積逆牌並用兩張逆抵消或使用殺'],
  ] as const).map(([id, name, owners, trigger, behaviour]) => ({
    id,
    name,
    owners: [...owners],
    trigger,
    behaviour,
    status: 'ok' as const,
    logHints: [name],
  })),
]
